package Formularios;

import Clases.Empleados;
import Utilidades.Empleado_Utilidades;
import Utilidades.vld_textbox;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class Frm_Empleado extends javax.swing.JInternalFrame {

    /**
     * Creates new form Frm_Empleado1
     */
    public Frm_Empleado() {
        initComponents();
        tabla();
        hilo.start();
    }

    public static String fechaActual() {
        Date Fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatoFecha.format(Fecha);

    }

    public String getHora() {
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        String date = sdf.format(new Date());
        return date;
    }
    Thread hilo = new Thread() {
        public void run() {
            for (int i = 0; i < 100000000; i++) {
                lblhora.setText(getHora().substring(0, 3));
                lblminutos.setText(getHora().substring(3, 6));
                lblsegundos.setText(getHora().substring(6, 8));
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(factura.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        busc = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        txtnombre = new javax.swing.JTextField();
        txtdirec = new javax.swing.JTextField();
        txtciudad = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        txtsalario = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtedad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtcargo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        date_fecha = new com.toedter.calendar.JDateChooser();
        txtsexo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_em = new javax.swing.JTable();
        salir = new javax.swing.JButton();
        lblfecha = new javax.swing.JLabel();
        lblhora = new javax.swing.JLabel();
        lblminutos = new javax.swing.JLabel();
        lblsegundos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Niagara Solid", 1, 48)); // NOI18N
        jLabel12.setText("Empleados");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 150, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1487471430_user-group-new.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel11.setFont(new java.awt.Font("Niagara Solid", 1, 24)); // NOI18N
        jLabel11.setText("Codigo");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        txtcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodigoKeyTyped(evt);
            }
        });
        getContentPane().add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 100, 30));

        busc.setText("BUSCAR");
        busc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscActionPerformed(evt);
            }
        });
        getContentPane().add(busc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 90, 30));

        btnInsertar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnInsertar.setForeground(new java.awt.Color(0, 0, 255));
        btnInsertar.setText("Guardar");
        btnInsertar.setBorderPainted(false);
        btnInsertar.setOpaque(false);
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, 38));

        btnModificar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(0, 0, 255));
        btnModificar.setText("Modificar");
        btnModificar.setOpaque(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, 38));

        btnEliminar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setOpaque(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 110, 40));

        jLabel14.setFont(new java.awt.Font("Niagara Solid", 1, 24)); // NOI18N
        jLabel14.setText("Salario:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Niagara Solid", 1, 24)); // NOI18N
        jLabel9.setText("Correo:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Niagara Solid", 1, 24)); // NOI18N
        jLabel7.setText("Ciudad:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Niagara Solid", 1, 24)); // NOI18N
        jLabel6.setText("Dirección:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Niagara Solid", 1, 24)); // NOI18N
        jLabel5.setText("Nombres:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Niagara Solid", 1, 24)); // NOI18N
        jLabel4.setText("Identificación:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        cbTipo.setBackground(new java.awt.Color(51, 0, 255));
        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "selecionar", "CEDULA", "RUC", "PASAPORTE" }));
        getContentPane().add(cbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 180, 30));

        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 320, 30));
        getContentPane().add(txtdirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 470, 30));

        txtciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtciudadKeyTyped(evt);
            }
        });
        getContentPane().add(txtciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 200, 30));

        txtcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorreoActionPerformed(evt);
            }
        });
        txtcorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcorreoKeyTyped(evt);
            }
        });
        getContentPane().add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 200, 30));

        txtsalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsalarioActionPerformed(evt);
            }
        });
        txtsalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsalarioKeyTyped(evt);
            }
        });
        getContentPane().add(txtsalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 200, 30));

        jLabel15.setFont(new java.awt.Font("Niagara Solid", 1, 24)); // NOI18N
        jLabel15.setText("Número:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, -1, -1));

        txtcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcedulaKeyTyped(evt);
            }
        });
        getContentPane().add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 210, 30));

        jLabel16.setFont(new java.awt.Font("Niagara Solid", 1, 24)); // NOI18N
        jLabel16.setText("Edad");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, -1, -1));

        txtedad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtedadKeyTyped(evt);
            }
        });
        getContentPane().add(txtedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 40, 30));

        jLabel2.setFont(new java.awt.Font("Niagara Solid", 1, 24)); // NOI18N
        jLabel2.setText("sexo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, -1, -1));

        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 190, 30));

        jLabel8.setFont(new java.awt.Font("Niagara Solid", 1, 24)); // NOI18N
        jLabel8.setText("Teléfono");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Niagara Solid", 1, 24)); // NOI18N
        jLabel10.setText("Cargo");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, -1, -1));
        getContentPane().add(txtcargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 200, 30));

        jLabel3.setFont(new java.awt.Font("Niagara Solid", 1, 24)); // NOI18N
        jLabel3.setText("Fecha de ingreso");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, -1, -1));
        getContentPane().add(date_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, -1, -1));

        txtsexo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsexoKeyTyped(evt);
            }
        });
        getContentPane().add(txtsexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, 40, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 830, 10));

        Tabla_em.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        Tabla_em.getTableHeader().setResizingAllowed(false);
        Tabla_em.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Tabla_em);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 840, 200));

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 330, 50, -1));

        lblfecha.setBackground(new java.awt.Color(51, 51, 51));
        lblfecha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblfecha.setText("SS");
        getContentPane().add(lblfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        lblhora.setBackground(new java.awt.Color(51, 51, 51));
        lblhora.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblhora.setText("HH");
        getContentPane().add(lblhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, -1));

        lblminutos.setBackground(new java.awt.Color(51, 51, 51));
        lblminutos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblminutos.setText("MM");
        getContentPane().add(lblminutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, -1, -1));

        lblsegundos.setBackground(new java.awt.Color(51, 51, 51));
        lblsegundos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblsegundos.setText("SS");
        getContentPane().add(lblsegundos, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoazulceleste.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 910, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoKeyTyped
        new vld_textbox().soloNumeros(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoKeyTyped

    private void buscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscActionPerformed

        Boolean confirma = false;
        for (Empleados elem : empleados) {
            if (txtcodigo.getText().equals(elem.getCodigo())) {
                codigo = elem.getCodigo();
                txtcargo.setText(elem.getCargo());
                txtcedula.setText(elem.getCedula());
                txtciudad.setText(elem.getCiudad());
                txtcorreo.setText(elem.getCorreo());
                txtdirec.setText(elem.getDireccion());
                txtedad.setText(elem.getEdad());
                txtnombre.setText(elem.getNombres());
                txtsalario.setText(elem.getSalario().toString());
                txtsexo.setText(elem.getGenero());
                txttelefono.setText(elem.getTelefono());
                cbTipo.setSelectedItem(elem.getTipo_doc());
                confirma = true;
                //date_fecha.setDate(elem.getFecha_registro());
            }
        }        // TODO add your handling code here:
        if (!confirma) {
            JOptionPane.showMessageDialog(null, "CEDULA NO REGISTRADA");
        }
    }//GEN-LAST:event_buscActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        if (!camposllenos()) {
            JOptionPane.showMessageDialog(null, "TODOS LOS CAMPOS SON OBLIGATORIOS");
            return;
        }
        try {
            Empleado_Utilidades eu = new Empleado_Utilidades();
            eu.setRuta("src\\Archivos\\empleados.txt");
            //List<Medicos> lista = new ArrayList();
            for (Empleados elem : empleados) {
                if (txtcodigo.getText().equals(elem.getCodigo())) {
                    JOptionPane.showMessageDialog(rootPane, "Paciente ya Registrado!!");
                    return;
                }
            }
            Empleados e = new Empleados();

            e.setCargo(txtcargo.getText());
            e.setCedula(txtcedula.getText());
            e.setCiudad(txtciudad.getText());
            e.setCodigo(txtcodigo.getText());
            e.setCorreo(txtcorreo.getText());
            e.setDireccion(txtdirec.getText());
            e.setEdad(txtedad.getText());
            e.setTelefono(txttelefono.getText());
            e.setFecha_registro(String.valueOf(date_fecha.getCalendar().get(Calendar.DAY_OF_MONTH)) + "/" + String.valueOf(date_fecha.getCalendar().get(Calendar.MONTH) + 1) + "/" + String.valueOf(date_fecha.getCalendar().get(Calendar.YEAR)).toString());
            e.setGenero(txtsexo.getText());
            e.setNombres(txtnombre.getText());
            e.setSalario(Double.parseDouble(txtsalario.getText()));
            e.setTipo_doc(cbTipo.getSelectedItem().toString());
            empleados.add(e);
            Empleado_Utilidades mun = new Empleado_Utilidades();
            mun.setRuta("src\\Archivos\\empleados.txt");
            mun.guardarEmpleado(empleados);
            JOptionPane.showMessageDialog(null, "Guardado con éxito!!");
            borrar();
            tabla();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "error");
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (!camposllenos()) {
            JOptionPane.showMessageDialog(null, "TODOS LOS CAMPOS SON OBLIGATORIOS");
            return;
        }
        try {
            remover:
            for (Empleados elem : empleados) {

                if (txtcodigo.getText().trim().equals(elem.getCodigo())) {
                    empleados.remove(elem);
                    break remover;
                }
            }
        } catch (Exception e) {
        }

        try {
            Empleados e = new Empleados();
            e.setCargo(txtcargo.getText());
            e.setCedula(txtcedula.getText());
            e.setCiudad(txtciudad.getText());
            e.setCodigo(txtcodigo.getText());
            e.setCorreo(txtcorreo.getText());
            e.setDireccion(txtdirec.getText());
            e.setEdad(txtedad.getText());
            e.setTelefono(txttelefono.getText());
            e.setFecha_registro(String.valueOf(date_fecha.getCalendar().get(Calendar.DAY_OF_MONTH)) + "/" + String.valueOf(date_fecha.getCalendar().get(Calendar.MONTH) + 1) + "/" + String.valueOf(date_fecha.getCalendar().get(Calendar.YEAR)).toString());
            e.setGenero(txtsexo.getText());
            e.setNombres(txtnombre.getText());
            e.setSalario(Double.parseDouble(txtsalario.getText()));
            e.setTipo_doc(cbTipo.getSelectedItem().toString());
            empleados.add(e);
            Empleado_Utilidades eu = new Empleado_Utilidades();
            eu.setRuta("src\\Archivos\\empleados.txt");

            eu.guardarEmpleado(empleados);

            JOptionPane.showMessageDialog(null, "Guardado con éxito!!");
            borrar();
            tabla();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "error");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    public Boolean camposllenos() {
        JTextField campos[] = {txtcargo, txtcedula, txtciudad, txtcodigo, txtcorreo, txtdirec, txtedad, txtnombre, txtsalario, txtsexo, txttelefono};
        if (new vld_textbox().camposLlenos(campos)) {
            if (new vld_textbox().validaCedula(txtcedula.getText())) {
                return true;
            } else {
                JOptionPane.showMessageDialog(null, "INGRESE UNA CEDULA VALIDA");
                return false;
            }
        }
        return false;
    }
    
    public void cargarPacientes() {
        File f = new File("src\\Archivos\\empleados.txt");
        try {

            if (f.exists()) {
                FileInputStream fis = new FileInputStream(f);
                ObjectInputStream ois = new ObjectInputStream(fis);
                empleados = (ArrayList<Empleados>) ois.readObject();
                fis.close();
                ois.close();
                System.out.println("archivo cargado");
            } else {
                f.createNewFile();
                System.out.println("archivo creado");
            }
        } catch (Exception e) {
        }
    }
    
    public void tabla() {

        String columnas[] = {"CODIGO", "TIPO DOCUMENTO" , "CEDULA", "NOMBRE", "EDAD", "GENERO", "DIRECCION" , "CIUDAD" , "TELEFONO" , "CORREO" , "CARGO" , "SALARIO" , "FECHA INGRESO"};
        DefaultTableModel tm = new DefaultTableModel(null, columnas);

        Empleado_Utilidades eu = new Empleado_Utilidades();
        eu.setRuta("src\\Archivos\\empleados.txt");

        List<Empleados> lista = new ArrayList();

        try {
            lista = eu.consultarEmpleados();

            for (Empleados elem : lista) {

                String registros[] = {elem.getCodigo(),elem.getTipo_doc(),elem.getCedula(), elem.getNombres(), elem.getEdad(), elem.getGenero(), elem.getDireccion(), elem.getCiudad(),elem.getTelefono(),elem.getCorreo(),elem.getCargo(),elem.getSalario().toString(),elem.getFecha_registro()};
                tm.addRow(registros);
            }

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "error");
        }

        Tabla_em.setModel(tm);
    }
    
    public void borrar() {
        txtcargo.setText("");
        txtcedula.setText("");
        txtciudad.setText("");
        txtcodigo.setText("");
        txtcorreo.setText("");
        txtdirec.setText("");
        txtedad.setText("");
        txtnombre.setText("");
        txtsalario.setText("");
        txtsexo.setText("");
        txttelefono.setText("");
        cbTipo.setSelectedItem("");
        date_fecha.setDate(new Date());
    }
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Empleado_Utilidades eu = new Empleado_Utilidades();
        eu.setRuta("src\\Archivos\\empleados.txt");

        for (Empleados elem : empleados) {

            if (codigo.equals(elem.getCodigo())) {
                empleados.remove(elem);
                eu.guardarEmpleado(empleados);

                JOptionPane.showMessageDialog(null, "Eliminado!!");
                borrar();
                tabla();
                return;
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        new vld_textbox().soloLetras(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtciudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtciudadKeyTyped
        new vld_textbox().soloLetras(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtciudadKeyTyped

    private void txtcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoActionPerformed

    private void txtcorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcorreoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoKeyTyped

    private void txtsalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsalarioActionPerformed

    private void txtsalarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsalarioKeyTyped
        new vld_textbox().soloNumeros(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtsalarioKeyTyped

    private void txtcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaKeyTyped
        new vld_textbox().soloNumeros(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtcedulaKeyTyped

    private void txtedadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtedadKeyTyped
        new vld_textbox().soloNumeros(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtedadKeyTyped

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
        new vld_textbox().soloNumeros(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoKeyTyped

    private void txtsexoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsexoKeyTyped
        new vld_textbox().soloLetras(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtsexoKeyTyped

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        cargarPacientes();
        lblfecha.setText(fechaActual());        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        lblhora.setText(getHora().substring(0, 3));
        lblminutos.setText(getHora().substring(3, 6));
        lblsegundos.setText(getHora().substring(6, 8));        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameActivated

    ArrayList<Empleados> empleados = new ArrayList();
    String codigo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_em;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton busc;
    private javax.swing.JComboBox<String> cbTipo;
    private com.toedter.calendar.JDateChooser date_fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblhora;
    private javax.swing.JLabel lblminutos;
    private javax.swing.JLabel lblsegundos;
    private javax.swing.JButton salir;
    private javax.swing.JTextField txtcargo;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtciudad;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdirec;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtsalario;
    private javax.swing.JTextField txtsexo;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
